Redirect to view claims on success, otherwise log error
ford-capstone-wayne-state/total-loss-process pull request #24
Opened 2019-02-12 23:58 UTC by ej3076

2019-02-12 23:59 UTC, sloan-seamus approved these changes

2019-02-13 00:03 UTC, dsifford requested changes

2019-02-13 00:03 UTC, dsifford commented on frontend/src/app/middleware/middleware.service.ts
> +          console.log(err);
Use an error dialog here instead.

https://alyle-ui.firebaseapp.com/components/dialog

2019-02-14 00:11 UTC, dsifford commented on frontend/src/app/middleware/middleware.service.ts
> +          console.log(err);
This can be fixed later. Just keep it in mind. We're good to merge this for now.

2019-02-14 00:11 UTC, dsifford approved these changes

2019-02-14 00:12 UTC, merged